### PR TITLE
[STALE - DO NOT REVIEW][P2P] Improve RainTree Testing Framework (Issue#85)

### LINKED ISSUE #85: [P2P] RainTree Redundancy Layer Implementation
# Objective
Implement and test RainTree's redundancy layer on top of the Pre2P module.

# Origin Document
[The Pocket Network V1 P2P Specification](https://github.com/pokt-network/pocket-network-protocol/tree/main/p2p), supported by [this explanation of RainTree](https://drive.google.com/file/d/1PaAWTx47nPSrM798lxfKv0GnhLthZLYm/view?usp=sharing) is partially implemented in the `pre2p/raintree` branch atop the `Pre2P` module at the time of creating this issue, but without the redundancy and cleanup layers.

This implementation has already been started and is available in the `pre2p/raintree_redundancy` branch at the time of writing this thread in https://github.com/pokt-network/pocket/pull/80.

The initial implementation of the redundancy layer code is available in the following commit: https://github.com/pokt-network/pocket/commit/756b0a09cd7b33a72b46e1690e4a858c6033792b.

# Goals
## Deliverables
- [ ] Fully implement the redundancy layers of RainTree including as described in the docs referenced by the `Origin Document` section:
   - [ ] 1. ACK/Adjust/Resend
   - [ ] 2. Redundancy layer
   - [ ] 3. Daisy Chain clean-up
- [ ] Update `raintree_utils_test.go` to add support for
  - [ ] Dead / faulty nodes
  - [ ] Partial visibility of the network
- [ ] Update the `README.md` (to be added in the `pre2p/raintree` soon) describing the added / modified code layout of `Pre2P module` with the new modifications

## Testing Methodology

1. Use `make test_pre2p` to run existing tests
2. Update the test suite in `raintree_utils_test.go` and add `raintree_redundancy_layer_test.go` int he same package with new tests
3. [Optional] Use `LocalNet` as described in `docs/development/README.md`
4. [Optional] Using `Telemetry` (if ready) to validate the results from (2)

## Non-goals
- Scaling LocalNet to many nodes
- Resolving tech debt or optimizing existing code
- Replacing P2P with Pre2P

Creator: @Olshansk 
Co-Owners: @andrewnguyen22

### PR DESCRIPTION
**Pull request by Olshansk**
## Description

Add documentation and improve the P2P RainTree testing framework.

## Issue

Incremental step to fixing [issue/85](https://github.com/pokt-network/pocket/issues/85)

## Type of change

Please mark the options that are relevant.

- [x] New feature, functionality or library
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Code health or cleanup
- [ ] Major breaking change
- [x] Documentation
- [ ] Other: <REPLACE_ME>

### Primary Changes
- Add a telemetry event for RainTree send which can be used for:
    - Telemetry of how RainTree is performing
    - More deterministic testing (i.e. matching on exact # messages received and sent over the network)
- Add a bit of documentation on how the test framework works in the README
- Add inline documentation related to details of the test framework

- Reorganize helpers for the testing framework so its easier to follow
- Single source of truth for the serviceURL between the shared code and the p2p testing framework

### Flyby changes
- Add a few TODOs throughout the code
- Remove `p2pConfig` in the p2p module struct
- Group p2p tests together in Makefile
- Remove some legacy pre2p code

## Testing

- [x] `make test_p2p`
- [ ] `make test_all`
- [ ] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested my changes using the available tooling
- [x] If applicable, I have made corresponding changes to related local or global README
- [ ] If applicable, I have added new diagrams using [mermaid.js](https://mermaid-js.github.io)
- [ ] If applicable, I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Olshansk** [comment]
@andrewnguyen22 Per your request to add documentation around how the test framework works, I realized there are ways to make the framework:
- Easier to understand
- More robust and deterministic
- More extensible
- More visibility by adding telemetry, which can also be used for testing

I think that this PR will require a fair amount of thought and effort to understand, so please spend some time to look over it when you have a chance. I think it makes our testing much more robust and will give us the power to track concrete visibility into how messages are being sent.

Once this is reviewed and merged into main, we can continue iterating on the redundancy layer in a follow up PR. You might need to update `TestRainTreeCommConfig` to account for redundancy logic or simply update the # network reads/writes appropriately.

An example (from the tests):

```go
func TestRainTreeNetworkCompleteTwentySevenNodes(t *testing.T) {
	// 	                                                                                                                    val_1
	// 	                                     ┌────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┐
	//                                    val_10                                                                                                                   val_1                                                                                                       val_19
	//            ┌──────────────────────────┴──────────────┬──────────────────────────────────────┐                                         ┌────────────────────────┴────────────┬──────────────────────────────────┐                                  ┌────────────────────────┴──────────────┬────────────────────────────────────┐
	//          val_16                                    val_10                                 val_22                                     val_7                                 val_1                             val_13                             val_25                                  val_19                                val_4
	//   ┌────────┴─────┬───────────┐              ┌────────┴─────┬───────────┐           ┌────────┴─────┬───────────┐              ┌────────┴────┬──────────┐             ┌───────┴────┬─────────┐          ┌────────┴─────┬──────────┐         ┌───────┴─────┬──────────┐             ┌────────┴─────┬───────────┐          ┌───────┴────┬──────────┐
	// val_20         val_16      val_24         val_14         val_10      val_18      val_26         val_22      val_12         val_11        val_7      val_15        val_5        val_1     val_9      val_17         val_13     val_3     val_2         val_25     val_6         val_23         val_19      val_27     val_8        val_4      val_21
	originatorNode := validatorId(1)
	var expectedCalls = TestRainTreeCommConfig{
		originatorNode:  {0, 6}, // {num_messages_received_over_network, num_messages_sent_over network}
		validatorId(2):  {1, 0},
		validatorId(3):  {1, 0},
		validatorId(4):  {1, 2},
		validatorId(5):  {1, 0},
		validatorId(6):  {1, 0},
		validatorId(7):  {1, 2},
		validatorId(8):  {1, 0},
		validatorId(9):  {1, 0},
		validatorId(10): {1, 4},
		validatorId(11): {1, 0},
		validatorId(12): {1, 0},
		validatorId(13): {1, 2},
		validatorId(14): {1, 0},
		validatorId(15): {1, 0},
		validatorId(16): {1, 2},
		validatorId(17): {1, 0},
		validatorId(18): {1, 0},
		validatorId(19): {1, 4},
		validatorId(20): {1, 0},
		validatorId(21): {1, 0},
		validatorId(22): {1, 2},
		validatorId(23): {1, 0},
		validatorId(24): {1, 0},
		validatorId(25): {1, 2},
		validatorId(26): {1, 0},
		validatorId(27): {1, 0},
	}
	testRainTreeCalls(t, originatorNode, expectedCalls)
}
```

**Comment by andrewnguyen22** [comment]
I see the documentation and this is a step in the right direction, the mocking is difficult for me to follow the path.

Can we discuss offline sometime in order to move this forward?

**Comment by Olshansk** [comment]
> Can we discuss offline sometime in order to move this forward?

Yea, definitely. I might not be able to do so this week but we'll make time to go through it.

> the mocking is difficult for me to follow the path.

Since I know you're blocked by my reviews, and we can't sync offline on it yet, I was hoping to make a request that you try to dive deeper into the library in the meantime.

For example, pull the branch and:
- Modify unclear variable names so they're more semantic and easy to understand
- Modify/refactor function names that are unclear
- Add comments / TODOs that don't make sense

I realize this ask is a bit pedantic and very non-fun, but would really appreciate if you do it. The main reasoning is that I tried to make it easily interpretable and understandable, but **if you cannot understand it**, then I don't think anyone else will. Given that the consensus module level testing follows a similar approach, this is an extremely big problem for the long-term health of the codebase.

**Comment by andrewnguyen22** [comment]
Review when you can

**Comment by Olshansk** [comment]
@andrewnguyen22 Thanks for the questions/comments/modifications. Made me rethink the readability after you asked, so I think we're heading in the right direction here.

Aside from 

> // TODO (Olshansk) why did these values change in between commits?

I made a modification to the business logic of `TestRainTreeConfig`. In particular, the way I was computing `numNetworkWrites` was incorrect. Rather than counting the number of writes that node makes to other nodes, it was computing the number of writes other nodes due to it, making it always equal to num reads. 

> // TODO (Olshansk) explain how these expected values are derived

The way we derive the number of reads & writes is a function of how RainTree works. E.g. if we have N nodes, with some names, and we determine who the originator is, we have to manually craft how many reads and writes each node does.   Hence, the little tree diagram above each test.

I used my python simulator to help me craft the tests. Do you think we should productionize it?

**Comment by andrewnguyen22** [comment]
Discussed offline recently in `protocol hour` - this PR is `stale` right now.

Need to see changes and conflict free before review

**Review by andrewnguyen22 — CHANGES_REQUESTED** [review]
Discussed offline recently in `protocol hour` - this PR is `stale` right now.

Need to see changes and conflict free before review

**Comment by Olshansk** [comment]
This will be descoped into several different issues:

1. Adding the Jupyter notebook to generate tests
2. Improving the counters & adding documentation (in #304)
3. Improving the tests

**Pull request closed without merging**
