### PR TITLE
[Persistence] Broken Tests on main regression fix - Issue #308 

### LINKED ISSUE #308: [Bug] Broken Tests on main after #235
## Objective

Fix broken bugs on main introduced by #235.

## Origin Document

#235 was a large PR that reintroduced a bug fixed by #282.

Specifically, in `runtime/test_artifacts/uti.go`, the addition of `os.Exit(0)`

```go
func CleanupPostgresDocker(_ *testing.M, pool *dockertest.Pool, resource *dockertest.Resource) {
	// You can't defer this because `os.Exit`` doesn't care for defer
	if err := pool.Purge(resource); err != nil {
		log.Fatalf("could not purge resource: %s", err)
	}
	os.Exit(0)
}
```

Ignores the `exitCode` in `persistence/test/setup_test.go`

```go
func TestMain(m *testing.M) {
	pool, resource, dbUrl := test_artifacts.SetupPostgresDocker()
	testPersistenceMod = newTestPersistenceModule(dbUrl)
	exitCode := m.Run()
	test_artifacts.CleanupPostgresDocker(m, pool, resource)
	os.Exit(exitCode)
}
```

Resulting in various errors committed to main:

Screen Shot 2022-10-18 at 10 12 52 AM

Doing a hard reset to the prior commit (`git reset --hard 2c390c3c055b4d1a36fb93075867bcf96b89fdcd`) validated that these tests were functional in the previous commit.

## Goals

- `make develop_test` should pass after removing `os.Exit(0)` from `runtime/test_artifacts/util.go`

## Deliverable

- [ ] Removal of `os.Exit(0)` in `runtime/test_artifacts/util.go`
- [ ] Fixes in all broken tests raised by `make test_all`

## Non-goals / Non-deliverables

- New functionality
- Refactoring / organizing existing code

## Testing Methodology

- **All tests**: `make develop_test`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @Olshansk 
**Co-Owners**: @deblasis

### PR DESCRIPTION
**Pull request by deblasis**
## Description

This PR fixes a regression that was hiding an actual bug in the code.

## Issue

Fixes #308 

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Making sure that the test harness returns the right return code to the OS
- Added missing mappings

## Testing

- [x] `make develop_test`
- [x] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my changes using the available tooling
- [x] I have updated the corresponding CHANGELOG

### If Applicable Checklist
- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

### CODE REVIEW

**Review by Olshansk — COMMENTED** [review]
Ty! 💯

**Review by andrewnguyen22 — APPROVED** [review]

**Comment by andrewnguyen22** [comment]
NOTE: 

```golang
func toPersistenceActor(actor modules.Actor) *Actor {
	return &Actor{
		ActorType:       actor.GetActorTyp().(ActorType),
		Address:         actor.GetAddress(),
		PublicKey:       actor.GetPublicKey(),
		Chains:          actor.GetChains(),
		GenericParam:    actor.GetGenericParam(),
		StakedAmount:    actor.GetStakedAmount(),
		PausedHeight:    actor.GetPausedHeight(),
		UnstakingHeight: actor.GetUnstakingHeight(),
		Output:          actor.GetOutput(),
	}
}
```

Is already on main from my last PR

**Comment by Olshansk** [comment]
Since @deblasis is OOO, I merged this with main and it is indeed just a one line change (removing `os.Exit(0)`) after fixing merge conflicts. Confirmed that tests pass too, so @deblasis, feel free to merge when you're back in.

**Review by Olshansk — APPROVED** [review]

**Comment by Olshansk** [comment]
Will also need to add this one line to fix a regression on main

Screen Shot 2022-10-22 at 9 15 52 PM

**Pull request merged**
