### PR TITLE
[Automation] prevent PR merging depending on label/PR title (Issue #160)

### LINKED ISSUE #160: [Automation] prevent PR merging depending on label/PR title
# Objective

Introduce a Github action that forbids PR merging whenever the PR in question has a label `do not merge` or `WIP` in its title.

# Origin Document

While working on https://github.com/pokt-network/pocket/pull/139 we ended up having an "almost complete" work but we wanted to avoid an accidental merge.

image

This PR introduces the automation and perhaps a more precise representation of the current "state of the art".

# Goals / Deliverables
- [ ] Create a GH action

# Testing Methodology
- Make sure that the workflow treats correctly PRs that:
  - Have the "do not merge" label
  - Have "WIP" in their title
  - Do not have any of the above

---

Creator: @deblasis
Co-Owners: @Olshansk

### PR DESCRIPTION
**Pull request by deblasis**
## Description

This PR introduces a Github action to prevent merging if certain conditions are not met

Fixes [issue/160](https://github.com/pokt-network/pocket/issues/160)

## Type of change
Please mark the options that are relevant.

- [x] Other (Automation)

## How Has This Been Tested?

I have created the repository https://github.com/deblasis/dontmerge

Then I have created the 3 test scenarios here:
https://github.com/deblasis/dontmerge/pulls
image

This is what happens when the workflow encounters the label or the word WIP in the title:
image

## Checklist
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my changes using the available tooling
- [x] If applicable, I have made corresponding changes to related or global README
- [x] If applicable, I have added added new diagrams using [mermaid.js](https://mermaid-js.github.io)
- [x] If applicable, I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by andrewnguyen22 — APPROVED** [review]

**Comment by Olshansk** [comment]
This is perfect. Thank you @deblasis!

**Comment by Olshansk** [comment]
Screen Shot 2022-08-11 at 6 52 56 PM

**Comment by deblasis** [comment]
> Created [here](https://github.com/pokt-network/pocket/issues/labels) Screen Shot 2022-08-11 at 6 52 56 PM

Nice, but the tag should be `do not merge` with spaces not dashes 🙂

I used spaces because I saw `code health` and not `code-health`.

**Comment by Olshansk** [comment]
Updated!

**Pull request merged**
