### PR TITLE
V1 Prototype - Milestone

### PR DESCRIPTION
**Pull request by Olshansk**
## Description

This PR is meant to close out the V1 Prototype Milestone and continue iteration, research and development in subsequent milestones with smaller scopes. https://github.com/pokt-network/pocket/milestone/1

After the pre-prototype was first completed in mid-February of 2022, this is the first major milestone of V1 containing:
* **Utility**: A foundation for a pocket-specific proof-of-stake codebase w/o pocket-specific functionality.
* **Consensus**: A first iteration of HotPOKT.
* **PrePersistence**: An in-memory module mocking a real persistence layer.
* **Pre2P**: A basic peer-to-peer network module using Golang's std libraries.

The tooling, documentation and instruction in this foundation will enable external community members to start participating in the iteration and design of Pocket Network V1.

## Type of change
Please mark the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Fixes Issue
* https://github.com/pokt-network/pocket/issues/20
* https://github.com/pokt-network/pocket/issues/21

## How Has This Been Tested?

See `docs/development/README.md` for dependencies to install and follow the instructions below. Note that the instructions below are copied over from the same README.

### Setup

```bash
$ git clone git@github.com:pokt-network/pocket.git pocket_milestone_v1_prototype && cd pocket_milestone_v1_prototype
$ git checkout -b milestone/v1-prototype remotes/origin/milestone/v1-prototype
$ make protogen_clean && make protogen_local
$ make mockgen
$ make go_clean_deps
```

#### Unit Tests

```bash
$ make test_all
```

_This simply runs `go test -p=1 -count=1 ./...` under the hood._

Note that there are a few tests in the library that are prone to race conditions and we are working on improving them. This can be checked with `make test_race`.

#### LocalNet

1. Delete any previous docker state

```bash
$ make docker_wipe
```

2. In one shell, run the 4 nodes setup:

```bash
$ make compose_and_watch
```

4. In another shell, run the development client:

```bash
$ make client_start && make client_connect
```

4. Check the state of each node:

```bash
✔ PrintNodeState
```

5. Trigger the next view to ensure everything is working:

```bash
✔ TriggerNextView
```

6. Reset the ResetToGenesis if you want to:

```bash
✔ ResetToGenesis
```

7. Set the client to automatic and watch it go:

```bash
✔ TogglePacemakerMode
✔ TriggerNextView
```

8. [Optional] Common manual set of verification steps

```bash
✔ ResetToGenesis
✔ PrintNodeState # Check committed height is 0
✔ TriggerNextView
✔ PrintNodeState # Check committed height is 1
✔ TriggerNextView
✔ PrintNodeState # Check committed height is 2
✔ TogglePacemakerMode # Check that it’s automatic now
✔ TriggerNextView # Let it rip!
```

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] No new warnings are generated by my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Olshansk** [comment]
@guettomusick @andrewnguyen22 I'd like to merge this into main so our work is more easily accessible & readable by others to get community involvement.

@derrandz is helping me cleanup the Github issues in parallel so it's easier to see future and ongoing work.

**Review by derrandz — APPROVED** [review]
My symbolic approval to let this merge, as all of this code has been reviewed before.

**Review by guettomusick — APPROVED** [review]
Milestone Merge. LGTM

**Comment by andrewnguyen22** [comment]
I'm having this issue during `make test_all`:
```
> make protogen_clean
> make protogen_local
> go mod vendor && go mod tidy
> make test_all
?   	github.com/pokt-network/pocket/app/client	[no test files]
?   	github.com/pokt-network/pocket/app/pocket	[no test files]
?   	github.com/pokt-network/pocket/consensus	[no test files]
ok  	github.com/pokt-network/pocket/consensus/consensus_tests	(cached)
?   	github.com/pokt-network/pocket/consensus/leader_election	[no test files]
ok  	github.com/pokt-network/pocket/consensus/leader_election/sortition	(cached)
ok  	github.com/pokt-network/pocket/consensus/leader_election/vrf	(cached)
?   	github.com/pokt-network/pocket/consensus/types	[no test files]
ok  	github.com/pokt-network/pocket/p2p	(cached)
?   	github.com/pokt-network/pocket/p2p/pre2p	[no test files]
?   	github.com/pokt-network/pocket/p2p/pre2p/types	[no test files]
# github.com/pokt-network/pocket/p2p/pre2p/types/mocks
p2p/pre2p/types/mocks/network_mock.go:53:43: undefined: types.AddrBook
p2p/pre2p/types/mocks/network_mock.go:56:27: undefined: types.AddrBook
ok  	github.com/pokt-network/pocket/p2p/types	(cached)
ok  	github.com/pokt-network/pocket/persistence/pre_persistence	(cached)
ok  	github.com/pokt-network/pocket/shared/config	(cached)
ok  	github.com/pokt-network/pocket/shared/tests/utility_module	(cached)
ok  	github.com/pokt-network/pocket/shared/types	(cached)
ok  	github.com/pokt-network/pocket/shared/types/genesis	(cached)
ok  	github.com/pokt-network/pocket/utility/types	(cached)
```

**Comment by andrewnguyen22** [comment]
@derrandz @guettomusick were you able to run the tests okay?

**Review by andrewnguyen22 — APPROVED** [review]

**Comment by Olshansk** [comment]
**One small merge for Pocket, one giant milestone for Pocketbeings.**

Thank you @andrewnguyen22 for helping triple-check that the tests are passing and LocalNet works on a clean build and not just on my machine.

**Pull request merged**
