### PR TITLE
Build & Release versioning documentation update

### PR DESCRIPTION
**Pull request by Olshansk**
## Description
Documentation update on how to manage build & release versions & tags.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested?
NA

## Checklist:
NA

### CODE REVIEW

**Review by luyzdeleon — COMMENTED** [review]
I wonder if our versioning should take into consideration which version of the specs this implementation reflects: https://github.com/pokt-network/pocket-network-protocol ?

**Review by iajrz — CHANGES_REQUESTED** [review]
I noticed the proposed use of `X.Y.Z-pre-alpha`; bear in mind that because of semver's rules this is a bigger version than `X.Y.Z-alpha`, with an opposite result than intended.

Given closer analysis of semver 2, the build and hash information should not be separated by a '/' but a '+'.

Furthermore, because the intention is for branch and hash be informative, those should be separated with "+" not a "-", otherwise the branch name becomes meaningful when comparing versions.

So a potential version number should look like:

`X.Y.Z[-<pre_release_tag][+branch_name][+short_hash][+dirty]`

With the understanding that the tag is prefixed with `v` as usual with go projects, and the tag name contains the `X.Y.Z[-<pre_release_tag]` portion of the version pattern.

**Comment by luyzdeleon** [comment]
@iajrz I believe this PR proposes to move away from semver to https://go.dev/doc/modules/version-numbers

**Comment by Olshansk** [comment]
@iajrz I tried to account for your explanation in this commit: https://github.com/pokt-network/pocket/pull/91/commits/047b85b98dee772d67ceeef98d4e7ca5e28ab3c3

I also changed the first release to `v0.0.1-alpha.pre.1` per your comment.

Lmk if all of this makes sense.

**Review by iajrz — APPROVED** [review]

**Review by luyzdeleon — APPROVED** [review]

**Pull request merged**
