### PR TITLE
[BUG] Tilt - Update permissions to avoid using sudo

### PR DESCRIPTION
**Pull request by Olshansk**
## Description

Fix Tilt permissions issue

## Issue

Main build is broken as seen [here](https://github.com/pokt-network/pocket/actions/runs/4116795739/jobs/7107384911#step:7:894).

Screenshot 2023-02-07 at 11 52 00 AM

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Add `ENV PATH $PATH:$HOME/.local/bin` to `dev` and `prod` images

### CODE REVIEW

**Review by deblasis — APPROVED** [review]
There's 1% of me that thinks that it should be a oneliner 
```
ENV PATH $PATH:$GOPATH/bin:$HOME/.local/bin
```
but LGTM 🚢

**Comment by okdas** [comment]
> There's 1% of me that thinks that it should be a oneliner
> 
> ```
> ENV PATH $PATH:$GOPATH/bin:$HOME/.local/bin
> ```
> 
> but LGTM 🚢

@deblasis Bingo! You're 100% correct. But we are utilizing official golang image that already has this dir in a PATH envar! :)

**Review by okdas — APPROVED** [review]
LGTM!

**Comment by Olshansk** [comment]
@deblasis I think I'll just go ahead and remove line 9.

**Pull request merged**
