### PR TITLE
[Core] Productionize End-to-end tx from iteration 3 demo

### LINKED ISSUE #364: [Core] Localnet happy path end-to-end transaction (iteration 3 demo)
## Objective

Productionize iteration 3 demo for an end-to-end transaction

## Origin Document

This is a "spin off" from #325

## Goals

- LocalNet happy path end-to-end transaction

## Deliverable

- [ ] Productionize the last few commits from this branch: https://github.com/pokt-network/pocket/tree/iteration3_demo
- [ ] Instructions on how to follow the commands in [this video](https://drive.google.com/file/d/1IOrzq-XJP04BJjyqPPpPu873aSfwrnur/view?usp=share_link) locally

## Non-goals / Non-deliverables

- Expanding the scope to unhappy paths
- Validating transaction fees

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references

## Testing Methodology

- [ ] Instructions for iteration 3 demo
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @Olshansk

### PR DESCRIPTION
**Pull request by Olshansk**
## Description

Productionze the changes made to iteration 3 demo.

## Issue

Fixes #364 

## Type of change

Please mark the relevant option(s):

- [x] New feature, functionality or library
- [x] Bug fix
- [x] Code health or cleanup
- [x] Major breaking change
- [x] Documentation
- [ ] Other 

## List of changes

In addition to make the CLI broadcast a transaction, two major breaking changes were made
- Changed the scope of `TransactionExists` from the `PostgresContext` to the `PersistenceModule`
- Changed the scope of `CheckTransaction` from the `UtilityContext` to the `UtilityModule`

The reason for this change is because the codebase was creating unnecessary contexts when the module directly could be used. In particular, access to the `mempool` and the `txIndexer` is not scope to a `context` but exists in the lifecycle of the entire node. Making these changes simplified the code, end-to-end flow and is also beginning to set us up for cleaner rollbacks where contexts can be just cleared & released.

#### Shared Changes
- Changed the scope of `TransactionExists` from the `PostgresContext` to the `PersistenceModule`
- Changed the scope of `CheckTransaction` from the `UtilityContext` to the `UtilityModule`
- Change the `bus` to be a pointer receiver rather than a value receiver in all the functions it implements

#### RPC Changes
- Updated `PostV1ClientBroadcastTxSync` to broadcast the transaction it receives
- Avoid creating an unnecessary utility context and use the utility module directly

#### Utility Module Changes
- Introduce a general purpose `HandleMessage` method at the utility level
- Move the scope of `CheckTransaction` from the context to the module level
- Add an `IsEmpty` function to the `Mempool`
- Rename `DeleteTransaction` to `RemoveTransaction` in the mempool
- Rename `LatestHeight` to `Height` in the `utilityContext`
- Add comments inside `CheckTransaction` so its functionality is clearer
- Add comments and cleanup the code in `mempool.go`

#### Consensus Changes
- Removed unused `consensus.UtilityMessage`

#### Persistence Changes
- Changed the scope of `TransactionExists` from the `PostgresContext` to the `PersistenceModule`

## Testing

- [x] `make develop_test`
- [ ] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`
- [ ] Followed the instructions at `docs/demos/iteration_3_end_to_end_tx.md`

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested my changes using the available tooling
- [x] I have updated the corresponding CHANGELOG

### If Applicable Checklist
- [ ] I have updated the corresponding README(s); local and/or global
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

### CODE REVIEW

**Comment by Olshansk** [comment]
I've added 3 reviewers to this PR.

@jessicadaugherty - Please only focus on the documentation and instructions in `docs/demos/iteration_3_end_to_end_tx.md` as we will likely follow something similar for future demos.

@deblasis - Please provide feedback on overall code structure, health, cross-module interaction, etc. In particular, the changes in the scoping of some of the methods will be important for rolling back contexts in the future.

@oten91 - No need to do a deep review, but I'd appreciate your opinion on `TransactionGossipMessage` and how I am using this in the application-specific bus entrypoint (i.e. `shared/node.go`). I personally think this is beginning to set us up for a good pattern to leverage the "central nervous system" of handling events, but POV given your hands-on experience would be very valuable.

**Review by deblasis — APPROVED** [review]
Solid work. Nice comments etc.

Minor things out of scope is probably gonna be around consolidating the way we access stuff like `txIndexer` not here and now :)

**Comment by Olshansk** [comment]
@jessicadaugherty Please approve the PR if it looks good to you.

@deblasis I think the build keeps failing because of #380, so PTAL at that as well.

@oten91 Once the build passes, I'll merge in even if you don't have time to take a look apriori, but would still really appreciate your feedback that we can follow up on in later PRs.

**Comment by deblasis** [comment]
@Olshansk 👍 #380 is on my list, I'm gonna give it another stab after my next PR

**Comment by Olshansk** [comment]
@deblasis Just a heads up that I pushed one more commit to fix an outstanding unit test: [`689f271` (#370)](https://github.com/pokt-network/pocket/pull/370/commits/689f271a5321dd6db1f46fb014013301b6e61798), related to #388 which I assigned to you.

I'm going to go ahead and merge since we've reviewed the rest of the code but let me know if you see a need for any follow-ups.

**Pull request merged**
