### PR TITLE
Refactoring the assignment order of the RunCommand function in validatorPod

### PR DESCRIPTION
**Pull request by innocent-saeed36**
In the validatorPod struct's RunCommand method, there has been a minor, yet significant change in the order of operations to ensure that the result field of the validatorPod struct correctly captures the full command result.

In the previous version of the method, the command result struct r was assigned to v.result before r.Stdout was populated with the command output. This meant that v.result always contained an empty string for its Stdout field, regardless of the command's actual output.

This has now been corrected by moving the assignment of r to v.result below the line where r.Stdout is populated. This ensures that the Stdout field of v.result correctly contains the command's output, and not an empty string.

This change is important because it provides accurate command output information when referencing v.result, allowing for better debugging and error handling in the usage of validatorPod instances. While it might seem like a small change, it can significantly improve the transparency and traceability of command execution within the application.

## Issue

Fixes #<issue_number>

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Change #1
- Change #2
- ...

## Testing

- [ ] `make develop_test`; if any code changes were made
- [ ] [Docker Compose LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md); if any major functionality was changed or introduced
- [ ] [k8s LocalNet](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md); if any infrastructure or configuration changes were made

## Required Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

### CODE REVIEW

**Review by Olshansk — COMMENTED** [review]
@innocent-saeed36 Appreciate you looking into this.

1. This makes sense to me at a high level. But, given that we're dealing with pointers, I was surprised that this is the case. Any chance you can show a video or validate this with the addition of a new test?

2. Could you update the github description appropriately? We use it for git messages.

**Review by dylanlott — APPROVED** [review]
LGTM ✅ Confirmed on my local that this populates the Stdout field properly.

**Comment by Olshansk** [comment]
> LGTM ✅ Confirmed on my local that this populates the Stdout field properly.

@dylanlott For external contributors that are not core contributors (yet), we need to merge it ourselves after checks have passed.

**Comment by Olshansk** [comment]
Seeme like a harmless change, so we can merge it in.

**Pull request merged**
