### PR TITLE
[Main][Telemetry]: Merge the first part of the telemetry (metrics) milestone into main

### PR DESCRIPTION
**Pull request by derrandz**
## Description

This PR adds event-metrics to Pre2P RainTree implementation and the HotPOKT consensus implementation using the Telemetry module.

## Issues
This PR ticks off the deliverables 1, 2, 3, 4 from #101 

## Changes
Please mark the options that are relevant.

- [x] Added instrumentation to record the reception of a RainTree message as an event for each block, this event has the following attributes:
     - namespace `pre2p`
     - event_name `raintree_messages`
     - labels: [height]

- [x] Added instrumentation to record the reception of redundant RainTree messages as an event for each new block, the event has the following attributes:
     - namespace `pre2p`
     - event_name `broadcast_message_redundancy_per_block`
     - labels: [height, message_hash] 

- [x] Added `logql` query to process the recorded events and fed the results to a numerical series graph

- [x] Added instrumentation to record the reception of a hotpokt message as an event for each block, this event has the following attributes:
     - namespace `consensus`
     - event_name `hotpokt_messages`
     - labels: [height, step, validator_role]

- [x] Added logql query to process the recorded events and fed the results to a numerical series graph

## How Has This Been Tested?
__

1. Spin up the stack
```zsh
$ make compose_and_watch
```

2. Make sure you spin the client up, and that kick the blockchain off:
```zsh
$ make client_start && make client_connect
```

3. Choose:
```
✔ TogglePacemakerMode
✔ TriggerNextView
```

4. Open Grafana at [http://localhost:3000](http://localhost:3000)
5. Open the `RainTree/HotPokt Stats Dashboard v0.1`

6. Verify the results on the dashboard

### Additional items for review

The query that was used to generate the graph is the following:
```logql
sum by (blockheight) (count_over_time({host=\"docker-desktop\"}\n    |= \"[EVENT] event_metrics_namespace_consensus\"\n    | pattern `<datetime> <_> <time> <type> <_> <metric_name> <_> <blockheight> <step> <validator_role>`[6s]))"
```
6. Verify the results on the dashboard

### Additional items for review

The query that was used to generate the graph is the following:

1. Total # HotPOKT Msgs / Block
```sql
sum by (blockheight) (
   count_over_time({host="docker-desktop"}
   |= "[EVENT] consensus"
   | pattern `<datetime> <_> <time> <type> <_> <metric_name> <_> <blockheight> <step> <validator_role>`[6s]
   )
),
```

2. Avg # Raintree Msgs / Block

```sql
avg by (blockheight, instance) (
  sum by (blockheight) (
    count_over_time({host="docker-desktop"}
    |= "[EVENT] p2p raintree_messages"
    | pattern `<datetime> <_> <time> <type> <namespace> <metric> <_> <blockheight>`[6s])
  )
)
```

```sql
avg by (blockheight, instance) (
  sum by (blockheight) (
    count_over_time({host="docker-desktop"}
    |= "[EVENT] p2p broadcast_message_redundancy_per_block"
    | pattern `<datetime> <_> <time> <type> <_> <redundancy> <_> <hashstring> <_> <blockheight>`[6s])
   )
)
```

Owners: @derrandz 
Co-owners: @okdas @Olshansk

### CODE REVIEW

**Review by Olshansk — CHANGES_REQUESTED** [review]
@derrandz

1. Could you please merge with master and resolve the current conflicts?

For example, there's some outdated files from a long time ago being added back in.

Screen Shot 2022-08-03 at 11 16 39 AM

2. Can you please update the PR metadata (issue, labels, etc...)

3. Before we merge, can you confirm that `make test_all` and `LocalNet` function as expected as a final sanity check?

**Comment by derrandz** [comment]
Thanks @Olshansk for catching the tests.

We now have passing tests. `LocalNet` has been tested and it's working.

Screen Shot 2022-08-04 at 14 49 35
Screen Shot 2022-08-04 at 14 51 14

It's worth mentioning that the blockchain height gauge is slow to catch up with the rest of the metrics. Perhaps we should log this into an issue? @okdas Your opinion on the matter would matter.

Cheers,

**Comment by Olshansk** [comment]
@derrandz I ran LocalNet + tests + graphs locally and LGTM. Screenshots below for reference.

Screen Shot 2022-08-06 at 1 31 13 PM

Screen Shot 2022-08-06 at 1 31 08 PM

There are a couple small additions/changes I want to make, but I figured I can submit that for you to review as a follow-up since it's not a blocker.

**Review by Olshansk — APPROVED** [review]

**Comment by derrandz** [comment]
Kudos for the follow ups @Olshansk

Merging this.

**Pull request merged**
